### ISSUE TITLE
Symantec AMSI evidence page is 404'd, new one is from Broadcom

### ISSUE THREAD

**Issue by jeffmcjunkin** [subat0mik/whoamsi#1]
https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/symantec-security-software/endpoint-security-and-management/endpoint-protection/all/release-notes/Whats-new-for-Symantec-Endpoint-Protection-14_3-.html

I don't think I can PR wiki changes.

**Comment by subat0mik** [comment]
> https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/symantec-security-software/endpoint-security-and-management/endpoint-protection/all/release-notes/Whats-new-for-Symantec-Endpoint-Protection-14_3-.html
> 
> I don't think I can PR wiki changes.

Updated! Thanks for the help!
