### ISSUE TITLE
Sophos AMSI support 

### ISSUE THREAD

**Issue by kmkz** [subat0mik/whoamsi#2]
Hi,
Just a small issue for an update because of the récent Sophos implementation of AMSI since august 2020 for versions/products:
Central Server Core Agent 2.6.0,
Central Windows Core Agent 2.6.0
 
Infos:
https://support.sophos.com/support/s/article/KB-000039096?language=en_US

Thanks for maintaining this awesome resource!
kmkz

**Comment by subat0mik** [comment]
Thank you @kmkz ! I've updated the table to include this data.

**Comment by kmkz** [comment]
Thank you very much for this awesome and very useful project !
kmkz

Bien cordialement/Best Regards/Mat beschte Gréiss

Mr Bourbon Jean-Marie
12 rue Kummert
L-6743 Grevenmacher (LU)
Mobile: (+352) 661 523 211
